# Chapter 1

This is all about data structures in NumPy

In [83]:
import numpy as np

In [84]:
vector_row = np.array([1, 2, 3])
vector_col = np.array([[1], [2], [3]])
matrix = np.array([[1, 2], [1, 2], [1, 2]])

print(np.array_repr(vector_row))
print(np.array_repr(vector_col))
print(np.array_repr(matrix))

array([1, 2, 3])
array([[1],
       [2],
       [3]])
array([[1, 2],
       [1, 2],
       [1, 2]])


There is `np.mat([[1,2],[1,2]])` which would create a Matrix data structure, but arrays are apparently the de facto standard for some reason, see [numpy Matrix documentation](https://numpy.org/doc/2.1/reference/generated/numpy.matrix.html).

In [85]:
from scipy import sparse

In [86]:
some_matrix = np.array([[0, 0], [0, 1], [3, 0]])
some_matrix_sparse = sparse.csr_matrix(some_matrix)

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(some_matrix_sparse)
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


It is interesting to note that the print function of sparse matrices tells me the shape - the CSR representation is the same here!

In [87]:
zeroes = np.zeros(shape=5, dtype=int)
ones = np.full(shape=(10, 10), fill_value=1.337)
zeroes_sparse = sparse.csr_matrix(zeroes)

print(zeroes)
print(ones)
print(zeroes_sparse)

[0 0 0 0 0]
[[1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 0 stored elements and shape (1, 5)>


In [90]:
print(zeroes[3])
print(some_matrix[2])
print(some_matrix[-2])
print(some_matrix[1:])
print(some_matrix[:10000])

0
[3 0]
[0 1]
[[0 1]
 [3 0]]
[[0 0]
 [0 1]
 [3 0]]


Python is very interesting regarding slicing of arrays, element selection, and so on!