# Chapter 1

This is all about data structures in NumPy

In [26]:
import numpy as np

In [27]:
vector_row = np.array([1, 2, 3])
vector_col = np.array([[1], [2], [3]])
matrix = np.array([[1, 2], [1, 2], [1, 2]])

print(np.array_repr(vector_row))
print(np.array_repr(vector_col))
print(np.array_repr(matrix))

array([1, 2, 3])
array([[1],
       [2],
       [3]])
array([[1, 2],
       [1, 2],
       [1, 2]])


There is `np.mat([[1,2],[1,2]])` which would create a Matrix data structure, but arrays are apparently the de facto standard for some reason, see [numpy Matrix documentation](https://numpy.org/doc/2.1/reference/generated/numpy.matrix.html).

In [28]:
from scipy import sparse

In [29]:
some_matrix = np.array([[0, 0], [0, 1], [3, 0]])
some_matrix_sparse = sparse.csr_matrix(some_matrix)

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(some_matrix_sparse)
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


It is interesting to note that the print function of sparse matrices tells me the shape - the CSR representation is the same here!

In [30]:
zeroes = np.zeros(shape=5, dtype=int)
ones = np.full(shape=(10, 10), fill_value=1.337)
zeroes_sparse = sparse.csr_matrix(zeroes)

print(zeroes)
print(ones)
print(zeroes_sparse)

[0 0 0 0 0]
[[1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]
 [1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337 1.337]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 0 stored elements and shape (1, 5)>


In [31]:
print(zeroes[3])
print(some_matrix[2])
print(some_matrix[-2])
print(some_matrix[1:])
print(some_matrix[:10000])

0
[3 0]
[0 1]
[[0 1]
 [3 0]]
[[0 0]
 [0 1]
 [3 0]]


Python is very interesting regarding slicing of arrays, element selection, and so on!

In [32]:
another_matrix = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

another_matrix_sparse = sparse.csr_matrix(another_matrix)

print(another_matrix.shape)
print(another_matrix.size)
print(another_matrix.ndim)
print(another_matrix.nbytes)
print(another_matrix_sparse.data.nbytes +
      another_matrix_sparse.indptr.nbytes + another_matrix_sparse.indices.nbytes)

print(f"Actual matrix size: {matrix_large.nbytes}")
print(
    f"Actual sparsly populated matrix size: {matrix_large_sparse.data.nbytes + matrix_large_sparse.indptr.nbytes + matrix_large_sparse.indices.nbytes}")

(3, 4)
12
2
96
160
Actual matrix size: 240
Actual sparsly populated matrix size: 40


In [33]:
def add_100(i): return i + 100


vectorized_add_100 = np.vectorize(add_100)

another_matrix_plus_100 = vectorized_add_100(another_matrix)
print(another_matrix_plus_100)

broadcasting_add_100_to_another_matrix = another_matrix + 100
print(broadcasting_add_100_to_another_matrix)

hadamard = another_matrix * another_matrix
print(hadamard)

[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [34]:
min = np.min(another_matrix)
max = np.max(another_matrix)

min_col = np.min(another_matrix, axis=0)
max_col = np.max(another_matrix, axis=0)

min_row = np.min(another_matrix, axis=1)
max_row = np.max(another_matrix, axis=1)

print(f"min:{min}, max:{max}")
print(f"min col:{min_col}, max col:{max_col}")
print(f"min row:{min_row}, max row:{max_row}")

min:1, max:12
min col:[1 2 3 4], max col:[ 9 10 11 12]
min row:[1 5 9], max row:[ 4  8 12]


In [35]:
mean = np.mean(another_matrix)
var = np.var(another_matrix)
std = np.std(another_matrix)

print(f"mean:{mean}, var:{var}, std:{std}")

mean = np.mean(another_matrix, axis=0)
var = np.var(another_matrix, axis=0)
std = np.std(another_matrix, axis=0)

print(f"mean:{mean}, var:{var}, std:{std}")

mean = np.mean(another_matrix, axis=1)
var = np.var(another_matrix, axis=1)
std = np.std(another_matrix, axis=1)

print(f"mean:{mean}, var:{var}, std:{std}")

mean:6.5, var:11.916666666666666, std:3.452052529534663
mean:[5. 6. 7. 8.], var:[10.66666667 10.66666667 10.66666667 10.66666667], std:[3.26598632 3.26598632 3.26598632 3.26598632]
mean:[ 2.5  6.5 10.5], var:[1.25 1.25 1.25], std:[1.11803399 1.11803399 1.11803399]


In [36]:
print(f"Reshape (6,2):\n{another_matrix.reshape(6, 2)}")
print(f"Reshape (2,6):\n{another_matrix.reshape(2, 6)}")
print(f"Reshape (1,?):\n{another_matrix.reshape(1, -1)}")
print(f"Reshape (2,?):\n{another_matrix.reshape(2, -1)}")
print(f"Reshape (3,?):\n{another_matrix.reshape(3, -1)}")
print(f"Reshape (4,?):\n{another_matrix.reshape(4, -1)}")
print(f"Reshape (6,?):\n{another_matrix.reshape(6, -1)}")
print(f"Reshape (?):\n{another_matrix.reshape(-1)}")
print(f"Reshape (12):\n{another_matrix.reshape(12)}")

Reshape (6,2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Reshape (2,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshape (1,?):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Reshape (2,?):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshape (3,?):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape (4,?):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshape (6,?):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Reshape (?):
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape (12):
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [37]:
print(f"Flatten does the same thing as reshape(-1)")
print(f"{another_matrix.reshape(-1)}")
print(f"{another_matrix.flatten()}")
print(f"But reshape(1, -1) creates a matrix row vector instead of a simple vector!")
print(f"{another_matrix.reshape(1, -1)}")

ravel_matrix = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

print(f"ravel is supposed to be faster as it creates no copy: {
      ravel_matrix.ravel()}")

print(f"ravel with C-style order: {ravel_matrix.ravel(order='C')}")
print(f"ravel with Fortran-style order: {ravel_matrix.ravel(order='F')}")
print(f"ravel with Fortran-contigious style: {ravel_matrix.ravel(order='A')}")
print(f"ravel with memort order: {ravel_matrix.ravel(order='K')}")

Flatten does the same thing as reshape(-1)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
But reshape(1, -1) creates a matrix row vector instead of a simple vector!
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
ravel is supposed to be faster as it creates no copy: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel with C-style order: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel with Fortran-style order: [ 1  5  9  2  6 10  3  7 11  4  8 12]
ravel with Fortran-contigious style: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel with memort order: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
print(f"Transposed: {another_matrix.T}")
print(f"Strictly, vectors cannot be transposed: {
      np.array([1, 2, 3, 4, 5, 6]).T}")

print(f"But row/column vectors can be: {
      np.array([[1, 2, 3, 4, 5, 6]]).T}")

Transposed: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Strictly, vectors cannot be transposed: [1 2 3 4 5 6]
But row/column vectors can be: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [59]:
rank = np.linalg.matrix_rank(another_matrix)
diag = another_matrix.diagonal()
trace = another_matrix.trace()
dot = np.dot(another_matrix[0], another_matrix[-1])
dot_with_operator = another_matrix[0] @ another_matrix[-1]
plus = another_matrix + another_matrix_plus_100
minus = another_matrix - another_matrix_plus_100
multiply = another_matrix @ another_matrix.reshape(4, 3)  # or np.dot()
multiply_element_wise = another_matrix * another_matrix
inverse = np.linalg.inv(another_matrix[:2, :2])

print(f"Rank:\t\t{rank}")
print(f"Diagonal:\t{diag}")
print(f"Trace:\t\t{trace}")
print(f"Dot:\t\t{dot}")
print(f"Dot (op):\t{dot_with_operator}")
print(f"Plus:\n{plus}")
print(f"Minus:\n{minus}")
print(f"Multiply:\n{multiply}")
print(f"Hadamard:\n{multiply_element_wise}")
print(f"Inverse:\n{inverse}")

Rank:		2
Diagonal:	[ 1  6 11]
Trace:		18
Dot:		110
Dot (op):	110
Plus:
[[102 104 106 108]
 [110 112 114 116]
 [118 120 122 124]]
Minus:
[[-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]]
Multiply:
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]
Hadamard:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Inverse:
[[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [70]:
np.random.seed(0)

print(f"{np.random.random(3)}")
print(f"{np.random.randint(0, 11, 3)}")

[0.5488135  0.71518937 0.60276338]
[3 7 9]


There are many random and pseudo-random number generators, like normal logistic, and uniform distribution generators, to name a few