# Chapter 1

This is all about data structures in NumPy

In [7]:
import numpy as np

In [ ]:
vector_row = np.array([1, 2, 3])
vector_col = np.array([[1], [2], [3]])
matrix = np.array([[1, 2], [1, 2], [1, 2]])

print(np.array_repr(vector_row))
print(np.array_repr(vector_col))
print(np.array_repr(matrix))

array([1, 2, 3])
array([[1],
       [2],
       [3]])
array([[1, 2],
       [1, 2],
       [1, 2]])


There is `np.mat([[1,2],[1,2]])` which would create a Matrix data structure, but arrays are apparently the de facto standard for some reason, see [numpy Matrix documentation](https://numpy.org/doc/2.1/reference/generated/numpy.matrix.html).